---
name: Update flake
on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  flake-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          inputs: nixpkgs neovim-nightly
